name: AuroraCore
version: 1.0
api: ["3.0.0-ALPHA12, 3.0.0, 3.1.0, 3.2.0, 3.3.0, 3.4.0"]
author: EmeraldYT
main: Potatoe\Core
permissions:
  core.all:
    default: op
    description: Gives All Permissions
    children:
      core.cmd.all:
        default: op
        description: Gives All Commands Permissions
        children:
          core.cmd.feed:
            default: op
            description: /feed
          core.cmd.heal:
            default: op
            description: /heal
          core.cmd.nick:
            default: op
            description: /nick
          core.cmd.spawn:
           default: true
           description: /spawn
          core.cmd.vanish:
           default: op
           description: /vanish
      core.anti.bypass:
        default: op
        description: Bypass All anti Spam Features
        children:
          core.anti.bypass.advert:
            default: op
            description: Bypass AAnti-Advertising
          core.bypass.swear:
            default: op
            description: Bypass anti-Swearing
